name: Publish docker image

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker image
      run: |
        docker build . --tag ghcr.io/jsh32/mineboy:latest
        docker push ghcr.io/jsh32/mineboy:latest